### ISSUE TITLE
where can I download aging.h5ad data for scaling analysis

### ISSUE THREAD

**Issue by wanghf810501** [zhaofangyuan98/SDMBench#1]
Hi,
I want to try the script for Scalability analysis, could you tell me where can I down load the example data (aging.h5ad) used in the Scalability analysis?

**Comment by yuanzhiyuan** [comment]
please found the data in the SODB website: https://gene.ai.tencent.com/SpatialOmics/datasetList?biotechID=3. The data is also available in the original Cell paper.
