### ISSUE TITLE
No results for GraphST

### ISSUE THREAD

**Issue by Rsugihara01** [zhaofangyuan98/SDMBench#4]
Hi, thanks for great works.

I am trying to score my clustering results and your works help me alot.
I just want to ask is there any results for GraphST? 
In Fig2 of the paper, GraphST is mentioned , but I couldn't find it in the supplementary data or in your website.

Thank you very much for your time and assistance. I look forward to your response.

Best regards,
Rsugihara

**Comment by zhaofangyuan98** [comment]
Thank you for your question！ We have corrected the name “GraphST” on our website, please try again!
