### ISSUE TITLE
Leiden_ImagingBased.py file not reproducible

### ISSUE THREAD

**Issue by jmezallamosas** [zhaofangyuan98/SDMBench#9]
Hi!

Issue Description:
I have been trying to better understand the insights of the 'Benchmarking spatial clustering methods with spatially resolved transcriptomics data' paper and have tried to reproduce Fig. 6a from the osmFISH. It seems that some of the files in the 'SDMBench/SpatialClustering/' path are not reproducible, especially Leiden_ImagingBased.py, with some variables not being utilized or not generating the desired 11 clusters as shown in the paper. The n_comps parameter in 'sc.tl.pca(adata_leiden, n_comps=50, svd_solver='arpack')' cannot be more than 33. On top of this, the script produced > 11 Leiden clusters leading to the lack of reproducibility of Fig. 6a. 

Requested Support:
Could you possibly provide the code used to generate Fig. 6a, or share the parameters used in the aforementioned script to reproduce these results? Thanks!

![Screenshot 2024-06-28 at 6 11 07 PM](https://github.com/zhaofangyuan98/SDMBench/assets/64668476/7b88ef63-0780-4e38-a933-4e8cb696c02c)

**Comment by zhaofangyuan98** [comment]
hello!
For osmfish data, because the number of genes in osmfish data is relatively small, only 33 genes, it is necessary to reduce the value of "n_comps" when performing the sc.tl.pca (adata_1eiden, n_comps=50, svd_solver='arpack ') step. It is recommended to use n_comps=33.
